// Code generated by MockGen. DO NOT EDIT.
// Source: collector.go

// Package mock_collectors is a generated GoMock package.
package mock_collectors

import (
	reflect "reflect"

	types "github.com/ajaypanthagani/sugabred/types"
	gomock "github.com/golang/mock/gomock"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// CollectAll mocks base method.
func (m *MockCollector) CollectAll() (*types.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectAll")
	ret0, _ := ret[0].(*types.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectAll indicates an expected call of CollectAll.
func (mr *MockCollectorMockRecorder) CollectAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectAll", reflect.TypeOf((*MockCollector)(nil).CollectAll))
}
